apiVersion: v1
kind: Service
metadata:
  name: in-person-portal
spec:
  type: {{ .Values.service.type }}
  selector:
    app: in-person-portal
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.sorPort }}
      targetPort: sor
      protocol: TCP
      name: sor-api